---
- hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=86400
      tags: [ 'packages' ]
- import_playbook: playbooks/control.yml
- import_playbook: playbooks/database.yml
- import_playbook: playbooks/webserver.yml
- import_playbook: playbooks/loadbalancer.yml