---
  - name: install tools
    apt:
      name:
        - python3-pip
        - python3-virtualenv
        - python3-dev
        - python3-mysqldb
      state: present
    tags: [ 'packages' ]

  - name: install mysql-server
    apt: name=mysql-server state=present
    tags: [ 'packages' ]

  - name: copy template
    template: src=my.cnf.j2 dest=/etc/mysql/my.cnf mode=0644
    tags: [ 'configure' ]
    notify: restart mysql

  - name: ensure mysql started
    service: name=mysql state=started enabled=yes
    tags: [ 'service' ]

  - name: create databnase
    mysql_db: name={{ db_name }} state=present
    tags: [ 'configure' ]

  - name: create demo user
    mysql_user: name={{ db_user_name }} password={{ db_user_pass }} priv={{ db_name }}.*:ALL host='{{ db_user_host }}' state=present
    tags: [ 'configure' ]
    
